version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
