apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: meetup-profiq-com-tls
spec:
  secretName: meetup-profiq-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.meetup.profiq.com
  dnsNames:
    - api.meetup.profiq.com
  acme:
    config:
      - http01:
          ingress: ingress
        domains:
          - api.meetup.profiq.com
