apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: demo-chat
    servicePort: 80
  tls:
    - secretName: meetup-profiq-com-tls
      hosts:
        - meetup.profiq.com
